#!/bin/bash

IN="eDP1"
EXT="DP1-1"
EXT2="DP1-3"

if (xrandr | grep "$EXT disconnected"); then
    xrandr --output $EXT --off --output $IN --auto
else
    xrandr --output $IN --off --output $EXT --auto --output $EXT2 --auto --right-of DP1-1
    feh --bg-tile '/home/frank604/Pictures/img3.jpg' &
fi

