#!/usr/bin/env sh
# mount boxes by SSHFS

# Copyright (c) 2013 Jason W Ryan
# The MIT License (MIT) http://opensource.org/licenses/MIT


MOUNT_PREFIX=/media/
MOUNT_SOURCE=/home/jason

usage () {
    cat <<EOF
sshmnt -[c,s,u,h]
       -c XXXX
       -s XXXX
       -u unmount
       -h print this message

EOF
}

mnt(){
    if [ $# -ne 3 ]; then
       echo "Wrong parameters for mnt - host dir port" >&2
       return 1
    fi

    host="$1"
    dir="$2"
    port="$3"
    sshfs "$host":${MOUNT_SOURCE} ${MOUNT_PREFIX}"$dir" \
    -C -p "$port" -o reconnect \
}

umnt(){
    dir="$1"
    fusermount -u ${MOUNT_PREFIX}"$dir"
}

get_host(){
    # check if on LAN
    lan="$(ip addr | grep .110/)"

    if [ -z "$lan" ] ; then
        echo xxx.xxx.xxx.xxx
        return 0
    fi

    case "$1" in
        cent) echo 192.168.1.100 ;;
        sent) echo 192.168.1.200 ;;
           *) echo "Unknown Parameter" >&2 && return 1 ;;
    esac

}

case "$1" in
    -c) mnt $(get_host cent) XXXXX xxxx ;;
    -s) mnt $(get_host sent) XXXXX xxxx  ;;
    -u)
        mount | grep XXXX &>/dev/null && umnt XXXX
        mount | grep XXXX &>/dev/null && umnt XXXX
        ;;
     *) usage && exit 1 ;;
esac
